using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

public class HotelList<T1> : List<string> 
{
    public List<string> listofHotels()
    {
        var listHotel = new HotelList<string> {
        {"ACURABMK"},
        {"ALTISHOTEL"},
        {"BESTWESTERNSKYCITY"},
        {"CHECKINNHOTEL"},
        {"CLARENSHOTEL"},
        {"CROWNPLAZAOKHLA"},
        {"EDDISON"},
        {"EMBLEM"},
        {"EMBLEMGURGAON"},
        {"EXPSAROVARPORTICO"},
        {"FRASERSUITES"},
        {"HCITYPARK"},
        {"HOTELCHAUPAL"},
        {"HOTELDELHI37"},
        {"HOTELDIPLOMAT"},
        {"HOTELERA"},
        {"HOTELGRENVILLEBANQUE"},
        {"HOTELSHANTIPALACE"},
        {"HOTELSTAR"},
        {"HOTELTRANSIT"},
        {"HOTELVIVADESTINATION"},
        {"HYATTREGENCYGURGAON"},
        {"IBISHOTEL"},
        {"INTERNATIONALINN"},
        {"KEMPINSKIAMBIENCE"},
        {"KHOTEL"},
        {"PARKDEFENCECOLONY"},
        {"PARKLANDCHIRAGENCLAV"},
        {"PARKLANDGRANDKAPASHE"},
        {"PARKLANDKAILASHCOLON"},
        {"PARKLANDKALKAJI"},
        {"PARKLANDSAFDARJUNG"},
        {"QUALITYINN"},
        {"ROYALORCHID"},
        {"SATYAMRESIDENCY"},
        {"TAJPALACE"},
        {"THEDRANDHOTELBIZOTEL"},
        {"THELALITNEWDELHI"},
        {"THELEAGUE"},
        {"ZIPBYSPREEBLUESTONE"},
        {"COUNTRYINN"},
        {"DOUBLETREE"},
        {"ITCMAURYA"},
        {"LEELAKEMPINSKI"},
        {"PULMAN"},
        {"SONAHOSPITALITY"},
        {"PLLAZIO"},
        {"OBEROI"},
        {"TRIDENT"},
        {"KODHDFCEMPMAR13"},
        {"BESTWESTERN"},
        {"COUNTRYINNSEC12"},
        {"KINGSTON"},
        {"VATIKA"},
        {"COUNTRYINN&SUIT"},
        {"MADHUBAN"},
        {"VIVANTABYTAJ"},
        {"CROWNPLAZA"},
        {"THEUMRAO"},
        {"RAMADAGURGAONCENTRAL"},
        {"ROYALPARKPLAZA"},
        {"OBEROIDELHI"},
        {"STARGRANDVILLA"},
        {"THEROYALPARK"},
        {"GOLDENTULIP"},
        {"HOTELOSCAR"},
        {"KARONHOTELS"},
        {"BRISTOL"},
        {"GALAXY"},
        {"MAPPLEEXOTICA"},
        {"THESUNRISEHOUSE"},
        {"MAPPLEEMERALD"},
        {"GETSHOLIDAYS"},
        {"KEYOODLESNP"},
        {"KEYSHOTEL"},
        {"FORTUNEDJPARKAVENUE"},
        {"THEUPPAL"},
        {"HERITAGEVILLAGE"},
        {"OPTUSSAROVAR"},
        {"GINGERROOTS"},
        {"EROSMANAGED"},
        {"PEPPERMINTGURGAON"},
        {"PREMIERINN"},
        {"1589CITYMARK"},
        {"PARKPLAZAGGN"},
        {"CROWNEPLAZAROHINI"},
        {"THEAWESOMEFARMS"},
        {"TIVOLIGARDENRESORT"}
        };
        return listHotel;
    }
}


