//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoyalWebApp.EntityServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Proc_ViewAccountDetails_Result", Namespace="http://schemas.datacontract.org/2004/07/RoyalWcfService", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Proc_ViewAccountDetails_Result : System.Data.Objects.DataClasses.ComplexObject, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AnniversaryDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DOBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateonCardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DesignationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaritalStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MemberIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SalutationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address2 {
            get {
                return this.Address2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address2Field, value) != true)) {
                    this.Address2Field = value;
                    this.RaisePropertyChanged("Address2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AnniversaryDate {
            get {
                return this.AnniversaryDateField;
            }
            set {
                if ((object.ReferenceEquals(this.AnniversaryDateField, value) != true)) {
                    this.AnniversaryDateField = value;
                    this.RaisePropertyChanged("AnniversaryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardCode {
            get {
                return this.CardCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CardCodeField, value) != true)) {
                    this.CardCodeField = value;
                    this.RaisePropertyChanged("CardCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardName {
            get {
                return this.CardNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CardNameField, value) != true)) {
                    this.CardNameField = value;
                    this.RaisePropertyChanged("CardName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardNumber {
            get {
                return this.CardNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CardNumberField, value) != true)) {
                    this.CardNumberField = value;
                    this.RaisePropertyChanged("CardNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string County {
            get {
                return this.CountyField;
            }
            set {
                if ((object.ReferenceEquals(this.CountyField, value) != true)) {
                    this.CountyField = value;
                    this.RaisePropertyChanged("County");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DOB {
            get {
                return this.DOBField;
            }
            set {
                if ((object.ReferenceEquals(this.DOBField, value) != true)) {
                    this.DOBField = value;
                    this.RaisePropertyChanged("DOB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateonCard {
            get {
                return this.DateonCardField;
            }
            set {
                if ((this.DateonCardField.Equals(value) != true)) {
                    this.DateonCardField = value;
                    this.RaisePropertyChanged("DateonCard");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Designation {
            get {
                return this.DesignationField;
            }
            set {
                if ((object.ReferenceEquals(this.DesignationField, value) != true)) {
                    this.DesignationField = value;
                    this.RaisePropertyChanged("Designation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaritalStatus {
            get {
                return this.MaritalStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.MaritalStatusField, value) != true)) {
                    this.MaritalStatusField = value;
                    this.RaisePropertyChanged("MaritalStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MemberID {
            get {
                return this.MemberIDField;
            }
            set {
                if ((object.ReferenceEquals(this.MemberIDField, value) != true)) {
                    this.MemberIDField = value;
                    this.RaisePropertyChanged("MemberID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mobile {
            get {
                return this.MobileField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileField, value) != true)) {
                    this.MobileField = value;
                    this.RaisePropertyChanged("Mobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNo {
            get {
                return this.PhoneNoField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNoField, value) != true)) {
                    this.PhoneNoField = value;
                    this.RaisePropertyChanged("PhoneNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Salutation {
            get {
                return this.SalutationField;
            }
            set {
                if ((object.ReferenceEquals(this.SalutationField, value) != true)) {
                    this.SalutationField = value;
                    this.RaisePropertyChanged("Salutation");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Proc_InsertWebAccount_Result1", Namespace="http://schemas.datacontract.org/2004/07/RoyalWcfService", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Proc_InsertWebAccount_Result1 : System.Data.Objects.DataClasses.ComplexObject, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> tempwebidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> tempwebid {
            get {
                return this.tempwebidField;
            }
            set {
                if ((this.tempwebidField.Equals(value) != true)) {
                    this.tempwebidField = value;
                    this.RaisePropertyChanged("tempwebid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Proc_RegisterUsers_Result", Namespace="http://schemas.datacontract.org/2004/07/RoyalWcfService", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Proc_RegisterUsers_Result : System.Data.Objects.DataClasses.ComplexObject, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> tempwebidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> tempwebid {
            get {
                return this.tempwebidField;
            }
            set {
                if ((this.tempwebidField.Equals(value) != true)) {
                    this.tempwebidField = value;
                    this.RaisePropertyChanged("tempwebid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Proc_Login_Result", Namespace="http://schemas.datacontract.org/2004/07/RoyalWcfService", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Proc_Login_Result : System.Data.Objects.DataClasses.ComplexObject, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ERPMemberIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ERPMemberId {
            get {
                return this.ERPMemberIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ERPMemberIdField, value) != true)) {
                    this.ERPMemberIdField = value;
                    this.RaisePropertyChanged("ERPMemberId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Proc_ForgetPassword_Result", Namespace="http://schemas.datacontract.org/2004/07/RoyalWcfService", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Proc_ForgetPassword_Result : System.Data.Objects.DataClasses.ComplexObject, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Proc_GetTopWebId_Result1", Namespace="http://schemas.datacontract.org/2004/07/RoyalWcfService", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Proc_GetTopWebId_Result1 : System.Data.Objects.DataClasses.ComplexObject, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int No_Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int No_ {
            get {
                return this.No_Field;
            }
            set {
                if ((this.No_Field.Equals(value) != true)) {
                    this.No_Field = value;
                    this.RaisePropertyChanged("No_");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Proc_GetWebAccountByEmailId_Result", Namespace="http://schemas.datacontract.org/2004/07/RoyalWcfService", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Proc_GetWebAccountByEmailId_Result : System.Data.Objects.DataClasses.ComplexObject, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AnniversaryDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DOBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DesignationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaritalStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MemberIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SalutationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address2 {
            get {
                return this.Address2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address2Field, value) != true)) {
                    this.Address2Field = value;
                    this.RaisePropertyChanged("Address2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AnniversaryDate {
            get {
                return this.AnniversaryDateField;
            }
            set {
                if ((object.ReferenceEquals(this.AnniversaryDateField, value) != true)) {
                    this.AnniversaryDateField = value;
                    this.RaisePropertyChanged("AnniversaryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string County {
            get {
                return this.CountyField;
            }
            set {
                if ((object.ReferenceEquals(this.CountyField, value) != true)) {
                    this.CountyField = value;
                    this.RaisePropertyChanged("County");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DOB {
            get {
                return this.DOBField;
            }
            set {
                if ((object.ReferenceEquals(this.DOBField, value) != true)) {
                    this.DOBField = value;
                    this.RaisePropertyChanged("DOB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Designation {
            get {
                return this.DesignationField;
            }
            set {
                if ((object.ReferenceEquals(this.DesignationField, value) != true)) {
                    this.DesignationField = value;
                    this.RaisePropertyChanged("Designation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaritalStatus {
            get {
                return this.MaritalStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.MaritalStatusField, value) != true)) {
                    this.MaritalStatusField = value;
                    this.RaisePropertyChanged("MaritalStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MemberID {
            get {
                return this.MemberIDField;
            }
            set {
                if ((object.ReferenceEquals(this.MemberIDField, value) != true)) {
                    this.MemberIDField = value;
                    this.RaisePropertyChanged("MemberID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mobile {
            get {
                return this.MobileField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileField, value) != true)) {
                    this.MobileField = value;
                    this.RaisePropertyChanged("Mobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNo {
            get {
                return this.PhoneNoField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNoField, value) != true)) {
                    this.PhoneNoField = value;
                    this.RaisePropertyChanged("PhoneNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Salutation {
            get {
                return this.SalutationField;
            }
            set {
                if ((object.ReferenceEquals(this.SalutationField, value) != true)) {
                    this.SalutationField = value;
                    this.RaisePropertyChanged("Salutation");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Proc_AllTierDetails_Result", Namespace="http://schemas.datacontract.org/2004/07/RoyalWcfService", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Proc_AllTierDetails_Result : System.Data.Objects.DataClasses.ComplexObject, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> MaximumValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> MinimumValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> PointsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> MaximumValue {
            get {
                return this.MaximumValueField;
            }
            set {
                if ((this.MaximumValueField.Equals(value) != true)) {
                    this.MaximumValueField = value;
                    this.RaisePropertyChanged("MaximumValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> MinimumValue {
            get {
                return this.MinimumValueField;
            }
            set {
                if ((this.MinimumValueField.Equals(value) != true)) {
                    this.MinimumValueField = value;
                    this.RaisePropertyChanged("MinimumValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Points {
            get {
                return this.PointsField;
            }
            set {
                if ((this.PointsField.Equals(value) != true)) {
                    this.PointsField = value;
                    this.RaisePropertyChanged("Points");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Proc_TierDetails_Result", Namespace="http://schemas.datacontract.org/2004/07/RoyalWcfService", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Proc_TierDetails_Result : System.Data.Objects.DataClasses.ComplexObject, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> MaximumValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> MinimumValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> PointsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> MaximumValue {
            get {
                return this.MaximumValueField;
            }
            set {
                if ((this.MaximumValueField.Equals(value) != true)) {
                    this.MaximumValueField = value;
                    this.RaisePropertyChanged("MaximumValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> MinimumValue {
            get {
                return this.MinimumValueField;
            }
            set {
                if ((this.MinimumValueField.Equals(value) != true)) {
                    this.MinimumValueField = value;
                    this.RaisePropertyChanged("MinimumValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Points {
            get {
                return this.PointsField;
            }
            set {
                if ((this.PointsField.Equals(value) != true)) {
                    this.PointsField = value;
                    this.RaisePropertyChanged("Points");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Proc_PointStatment_Result", Namespace="http://schemas.datacontract.org/2004/07/RoyalWcfService", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Proc_PointStatment_Result : System.Data.Objects.DataClasses.ComplexObject, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateOfIssueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExpirationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PointTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> PointsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DateOfIssue {
            get {
                return this.DateOfIssueField;
            }
            set {
                if ((object.ReferenceEquals(this.DateOfIssueField, value) != true)) {
                    this.DateOfIssueField = value;
                    this.RaisePropertyChanged("DateOfIssue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExpirationDate {
            get {
                return this.ExpirationDateField;
            }
            set {
                if ((object.ReferenceEquals(this.ExpirationDateField, value) != true)) {
                    this.ExpirationDateField = value;
                    this.RaisePropertyChanged("ExpirationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PointType {
            get {
                return this.PointTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.PointTypeField, value) != true)) {
                    this.PointTypeField = value;
                    this.RaisePropertyChanged("PointType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Points {
            get {
                return this.PointsField;
            }
            set {
                if ((this.PointsField.Equals(value) != true)) {
                    this.PointsField = value;
                    this.RaisePropertyChanged("Points");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Proc_GetMemberBalance_Result", Namespace="http://schemas.datacontract.org/2004/07/RoyalWcfService", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Proc_GetMemberBalance_Result : System.Data.Objects.DataClasses.ComplexObject, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal After24HourPointsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MembershipIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> RechargeAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> RemainingAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal RemainingPointsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal After24HourPoints {
            get {
                return this.After24HourPointsField;
            }
            set {
                if ((this.After24HourPointsField.Equals(value) != true)) {
                    this.After24HourPointsField = value;
                    this.RaisePropertyChanged("After24HourPoints");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MembershipId {
            get {
                return this.MembershipIdField;
            }
            set {
                if ((object.ReferenceEquals(this.MembershipIdField, value) != true)) {
                    this.MembershipIdField = value;
                    this.RaisePropertyChanged("MembershipId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> RechargeAmount {
            get {
                return this.RechargeAmountField;
            }
            set {
                if ((this.RechargeAmountField.Equals(value) != true)) {
                    this.RechargeAmountField = value;
                    this.RaisePropertyChanged("RechargeAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> RemainingAmount {
            get {
                return this.RemainingAmountField;
            }
            set {
                if ((this.RemainingAmountField.Equals(value) != true)) {
                    this.RemainingAmountField = value;
                    this.RaisePropertyChanged("RemainingAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal RemainingPoints {
            get {
                return this.RemainingPointsField;
            }
            set {
                if ((this.RemainingPointsField.Equals(value) != true)) {
                    this.RemainingPointsField = value;
                    this.RaisePropertyChanged("RemainingPoints");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Proc_CardTransaction_Result", Namespace="http://schemas.datacontract.org/2004/07/RoyalWcfService", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Proc_CardTransaction_Result : System.Data.Objects.DataClasses.ComplexObject, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Transaction_IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Transaction_Id {
            get {
                return this.Transaction_IdField;
            }
            set {
                if ((object.ReferenceEquals(this.Transaction_IdField, value) != true)) {
                    this.Transaction_IdField = value;
                    this.RaisePropertyChanged("Transaction_Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Proc_GetWebAccountByTempWebId_Result", Namespace="http://schemas.datacontract.org/2004/07/RoyalWcfService", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Proc_GetWebAccountByTempWebId_Result : System.Data.Objects.DataClasses.ComplexObject, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AnniversaryDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DOBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DesignationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaritalStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Member_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SalutationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address2 {
            get {
                return this.Address2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address2Field, value) != true)) {
                    this.Address2Field = value;
                    this.RaisePropertyChanged("Address2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AnniversaryDate {
            get {
                return this.AnniversaryDateField;
            }
            set {
                if ((object.ReferenceEquals(this.AnniversaryDateField, value) != true)) {
                    this.AnniversaryDateField = value;
                    this.RaisePropertyChanged("AnniversaryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string County {
            get {
                return this.CountyField;
            }
            set {
                if ((object.ReferenceEquals(this.CountyField, value) != true)) {
                    this.CountyField = value;
                    this.RaisePropertyChanged("County");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DOB {
            get {
                return this.DOBField;
            }
            set {
                if ((object.ReferenceEquals(this.DOBField, value) != true)) {
                    this.DOBField = value;
                    this.RaisePropertyChanged("DOB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Designation {
            get {
                return this.DesignationField;
            }
            set {
                if ((object.ReferenceEquals(this.DesignationField, value) != true)) {
                    this.DesignationField = value;
                    this.RaisePropertyChanged("Designation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaritalStatus {
            get {
                return this.MaritalStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.MaritalStatusField, value) != true)) {
                    this.MaritalStatusField = value;
                    this.RaisePropertyChanged("MaritalStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Member_Id {
            get {
                return this.Member_IdField;
            }
            set {
                if ((object.ReferenceEquals(this.Member_IdField, value) != true)) {
                    this.Member_IdField = value;
                    this.RaisePropertyChanged("Member_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mobile {
            get {
                return this.MobileField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileField, value) != true)) {
                    this.MobileField = value;
                    this.RaisePropertyChanged("Mobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNo {
            get {
                return this.PhoneNoField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNoField, value) != true)) {
                    this.PhoneNoField = value;
                    this.RaisePropertyChanged("PhoneNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Salutation {
            get {
                return this.SalutationField;
            }
            set {
                if ((object.ReferenceEquals(this.SalutationField, value) != true)) {
                    this.SalutationField = value;
                    this.RaisePropertyChanged("Salutation");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EntityServiceReference.IEntityService")]
    public interface IEntityService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityService/GetUserDetails", ReplyAction="http://tempuri.org/IEntityService/GetUserDetailsResponse")]
        RoyalWebApp.EntityServiceReference.Proc_ViewAccountDetails_Result[] GetUserDetails(string memberId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityService/InsertUserDetails", ReplyAction="http://tempuri.org/IEntityService/InsertUserDetailsResponse")]
        RoyalWebApp.EntityServiceReference.Proc_InsertWebAccount_Result1[] InsertUserDetails(
                    string membershipid, 
                    string salutation, 
                    string firstName, 
                    string lastName, 
                    string address, 
                    string addressTwo, 
                    string city, 
                    string country, 
                    string phoneNo, 
                    string mobileNo, 
                    string email, 
                    System.DateTime dateOfBirth, 
                    System.DateTime anniversaryDate, 
                    string maritalStatus, 
                    string gender, 
                    decimal paymentAmount, 
                    System.DateTime paymentDate, 
                    string cardNo, 
                    string bankName, 
                    string userName, 
                    string password, 
                    string designation, 
                    bool boxOffiec, 
                    bool coupon);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityService/registeruserwithoutpayment", ReplyAction="http://tempuri.org/IEntityService/registeruserwithoutpaymentResponse")]
        RoyalWebApp.EntityServiceReference.Proc_RegisterUsers_Result[] registeruserwithoutpayment(
                    string membershipid, 
                    string salutation, 
                    string firstName, 
                    string lastName, 
                    string address, 
                    string addressTwo, 
                    string city, 
                    string country, 
                    string phoneNo, 
                    string mobileNo, 
                    string email, 
                    System.DateTime dateOfBirth, 
                    System.DateTime anniversaryDate, 
                    string maritalStatus, 
                    string gender, 
                    decimal paymentAmount, 
                    System.DateTime paymentDate, 
                    string cardNo, 
                    string bankName, 
                    string userName, 
                    string password, 
                    string designation, 
                    bool boxOffiec, 
                    bool coupon);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityService/GetUserLogin", ReplyAction="http://tempuri.org/IEntityService/GetUserLoginResponse")]
        RoyalWebApp.EntityServiceReference.Proc_Login_Result[] GetUserLogin(string Membershipid, string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityService/ChangePassword", ReplyAction="http://tempuri.org/IEntityService/ChangePasswordResponse")]
        int ChangePassword(string Membershipid, string oldpwd, string newpwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityService/ForgotPassword", ReplyAction="http://tempuri.org/IEntityService/ForgotPasswordResponse")]
        RoyalWebApp.EntityServiceReference.Proc_ForgetPassword_Result[] ForgotPassword(string Membershipid, string emailid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityService/UpdateUserDetails", ReplyAction="http://tempuri.org/IEntityService/UpdateUserDetailsResponse")]
        int UpdateUserDetails(string membershipid, string salutation, string firstName, string lastName, string address, string addressTwo, string city, string country, string mobileNo, string email, System.DateTime dateOfBirth, System.DateTime anniversaryDate, string maritalStatus, string designation, string phoneNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityService/GetMaxMemberId", ReplyAction="http://tempuri.org/IEntityService/GetMaxMemberIdResponse")]
        RoyalWebApp.EntityServiceReference.Proc_GetTopWebId_Result1[] GetMaxMemberId();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityService/GetUserDetailsByEmailId", ReplyAction="http://tempuri.org/IEntityService/GetUserDetailsByEmailIdResponse")]
        RoyalWebApp.EntityServiceReference.Proc_GetWebAccountByEmailId_Result[] GetUserDetailsByEmailId(string useremailid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityService/GetAllCardsDetails", ReplyAction="http://tempuri.org/IEntityService/GetAllCardsDetailsResponse")]
        RoyalWebApp.EntityServiceReference.Proc_AllTierDetails_Result[] GetAllCardsDetails();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityService/GetCardsDetailsbyType", ReplyAction="http://tempuri.org/IEntityService/GetCardsDetailsbyTypeResponse")]
        RoyalWebApp.EntityServiceReference.Proc_TierDetails_Result[] GetCardsDetailsbyType(string CardType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityService/UpdatePaymentDetails", ReplyAction="http://tempuri.org/IEntityService/UpdatePaymentDetailsResponse")]
        int UpdatePaymentDetails(string membershipid, int PayStatus, int Readytocreate, decimal paidamt, string receiptno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityService/GetPointStatusByMemberId", ReplyAction="http://tempuri.org/IEntityService/GetPointStatusByMemberIdResponse")]
        RoyalWebApp.EntityServiceReference.Proc_PointStatment_Result[] GetPointStatusByMemberId(string membershipid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityService/GetCardsBalanceByMemberId", ReplyAction="http://tempuri.org/IEntityService/GetCardsBalanceByMemberIdResponse")]
        RoyalWebApp.EntityServiceReference.Proc_GetMemberBalance_Result[] GetCardsBalanceByMemberId(string membershipid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityService/InsertTopUpDetails", ReplyAction="http://tempuri.org/IEntityService/InsertTopUpDetailsResponse")]
        RoyalWebApp.EntityServiceReference.Proc_CardTransaction_Result[] InsertTopUpDetails(string membershipid, decimal paidAmount, System.DateTime paiddate, string PaidReceiptNo, int TransType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityService/UpdateTopUpStatus", ReplyAction="http://tempuri.org/IEntityService/UpdateTopUpStatusResponse")]
        int UpdateTopUpStatus(string Transactionid, int success, int transType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityService/GetTempUserDetailsByWebId", ReplyAction="http://tempuri.org/IEntityService/GetTempUserDetailsByWebIdResponse")]
        RoyalWebApp.EntityServiceReference.Proc_GetWebAccountByTempWebId_Result[] GetTempUserDetailsByWebId(string tempwebid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityService/EmailExists", ReplyAction="http://tempuri.org/IEntityService/EmailExistsResponse")]
        int EmailExists(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityService/MobilenoExist", ReplyAction="http://tempuri.org/IEntityService/MobilenoExistResponse")]
        int MobilenoExist(string mobile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityService/FirstTimeLogin", ReplyAction="http://tempuri.org/IEntityService/FirstTimeLoginResponse")]
        int FirstTimeLogin(string memberid, System.DateTime doB);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityService/PasswordExistsCheck", ReplyAction="http://tempuri.org/IEntityService/PasswordExistsCheckResponse")]
        bool PasswordExistsCheck(string memberid, System.DateTime doB);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEntityServiceChannel : RoyalWebApp.EntityServiceReference.IEntityService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EntityServiceClient : System.ServiceModel.ClientBase<RoyalWebApp.EntityServiceReference.IEntityService>, RoyalWebApp.EntityServiceReference.IEntityService {
        
        public EntityServiceClient() {
        }
        
        public EntityServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EntityServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EntityServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EntityServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public RoyalWebApp.EntityServiceReference.Proc_ViewAccountDetails_Result[] GetUserDetails(string memberId) {
            return base.Channel.GetUserDetails(memberId);
        }
        
        public RoyalWebApp.EntityServiceReference.Proc_InsertWebAccount_Result1[] InsertUserDetails(
                    string membershipid, 
                    string salutation, 
                    string firstName, 
                    string lastName, 
                    string address, 
                    string addressTwo, 
                    string city, 
                    string country, 
                    string phoneNo, 
                    string mobileNo, 
                    string email, 
                    System.DateTime dateOfBirth, 
                    System.DateTime anniversaryDate, 
                    string maritalStatus, 
                    string gender, 
                    decimal paymentAmount, 
                    System.DateTime paymentDate, 
                    string cardNo, 
                    string bankName, 
                    string userName, 
                    string password, 
                    string designation, 
                    bool boxOffiec, 
                    bool coupon) {
            return base.Channel.InsertUserDetails(membershipid, salutation, firstName, lastName, address, addressTwo, city, country, phoneNo, mobileNo, email, dateOfBirth, anniversaryDate, maritalStatus, gender, paymentAmount, paymentDate, cardNo, bankName, userName, password, designation, boxOffiec, coupon);
        }
        
        public RoyalWebApp.EntityServiceReference.Proc_RegisterUsers_Result[] registeruserwithoutpayment(
                    string membershipid, 
                    string salutation, 
                    string firstName, 
                    string lastName, 
                    string address, 
                    string addressTwo, 
                    string city, 
                    string country, 
                    string phoneNo, 
                    string mobileNo, 
                    string email, 
                    System.DateTime dateOfBirth, 
                    System.DateTime anniversaryDate, 
                    string maritalStatus, 
                    string gender, 
                    decimal paymentAmount, 
                    System.DateTime paymentDate, 
                    string cardNo, 
                    string bankName, 
                    string userName, 
                    string password, 
                    string designation, 
                    bool boxOffiec, 
                    bool coupon) {
            return base.Channel.registeruserwithoutpayment(membershipid, salutation, firstName, lastName, address, addressTwo, city, country, phoneNo, mobileNo, email, dateOfBirth, anniversaryDate, maritalStatus, gender, paymentAmount, paymentDate, cardNo, bankName, userName, password, designation, boxOffiec, coupon);
        }
        
        public RoyalWebApp.EntityServiceReference.Proc_Login_Result[] GetUserLogin(string Membershipid, string pwd) {
            return base.Channel.GetUserLogin(Membershipid, pwd);
        }
        
        public int ChangePassword(string Membershipid, string oldpwd, string newpwd) {
            return base.Channel.ChangePassword(Membershipid, oldpwd, newpwd);
        }
        
        public RoyalWebApp.EntityServiceReference.Proc_ForgetPassword_Result[] ForgotPassword(string Membershipid, string emailid) {
            return base.Channel.ForgotPassword(Membershipid, emailid);
        }
        
        public int UpdateUserDetails(string membershipid, string salutation, string firstName, string lastName, string address, string addressTwo, string city, string country, string mobileNo, string email, System.DateTime dateOfBirth, System.DateTime anniversaryDate, string maritalStatus, string designation, string phoneNo) {
            return base.Channel.UpdateUserDetails(membershipid, salutation, firstName, lastName, address, addressTwo, city, country, mobileNo, email, dateOfBirth, anniversaryDate, maritalStatus, designation, phoneNo);
        }
        
        public RoyalWebApp.EntityServiceReference.Proc_GetTopWebId_Result1[] GetMaxMemberId() {
            return base.Channel.GetMaxMemberId();
        }
        
        public RoyalWebApp.EntityServiceReference.Proc_GetWebAccountByEmailId_Result[] GetUserDetailsByEmailId(string useremailid) {
            return base.Channel.GetUserDetailsByEmailId(useremailid);
        }
        
        public RoyalWebApp.EntityServiceReference.Proc_AllTierDetails_Result[] GetAllCardsDetails() {
            return base.Channel.GetAllCardsDetails();
        }
        
        public RoyalWebApp.EntityServiceReference.Proc_TierDetails_Result[] GetCardsDetailsbyType(string CardType) {
            return base.Channel.GetCardsDetailsbyType(CardType);
        }
        
        public int UpdatePaymentDetails(string membershipid, int PayStatus, int Readytocreate, decimal paidamt, string receiptno) {
            return base.Channel.UpdatePaymentDetails(membershipid, PayStatus, Readytocreate, paidamt, receiptno);
        }
        
        public RoyalWebApp.EntityServiceReference.Proc_PointStatment_Result[] GetPointStatusByMemberId(string membershipid) {
            return base.Channel.GetPointStatusByMemberId(membershipid);
        }
        
        public RoyalWebApp.EntityServiceReference.Proc_GetMemberBalance_Result[] GetCardsBalanceByMemberId(string membershipid) {
            return base.Channel.GetCardsBalanceByMemberId(membershipid);
        }
        
        public RoyalWebApp.EntityServiceReference.Proc_CardTransaction_Result[] InsertTopUpDetails(string membershipid, decimal paidAmount, System.DateTime paiddate, string PaidReceiptNo, int TransType) {
            return base.Channel.InsertTopUpDetails(membershipid, paidAmount, paiddate, PaidReceiptNo, TransType);
        }
        
        public int UpdateTopUpStatus(string Transactionid, int success, int transType) {
            return base.Channel.UpdateTopUpStatus(Transactionid, success, transType);
        }
        
        public RoyalWebApp.EntityServiceReference.Proc_GetWebAccountByTempWebId_Result[] GetTempUserDetailsByWebId(string tempwebid) {
            return base.Channel.GetTempUserDetailsByWebId(tempwebid);
        }
        
        public int EmailExists(string email) {
            return base.Channel.EmailExists(email);
        }
        
        public int MobilenoExist(string mobile) {
            return base.Channel.MobilenoExist(mobile);
        }
        
        public int FirstTimeLogin(string memberid, System.DateTime doB) {
            return base.Channel.FirstTimeLogin(memberid, doB);
        }
        
        public bool PasswordExistsCheck(string memberid, System.DateTime doB) {
            return base.Channel.PasswordExistsCheck(memberid, doB);
        }
    }
}
